"""
MADDPG baseline for the user's current simplified DDPG/SAC environment.

Compatibility:
- TensorFlow 2.16+ / Keras 3
- Python 3.10+
- Uses tf.keras.Model and tf.GradientTape

Fair-comparison design:
1. Same K=10, 2000 episodes, 100 steps, gamma, tau, learning rates,
   replay capacity, batch size, reward, and state dynamics as the current scripts.
2. Same master seed 0.
3. Environment trajectories are generated by a dedicated RNG, so policy/exploration
   random draws do not alter user-motion/channel trajectories.
4. Each of K agents outputs one scalar local action. To preserve the original
   one-scalar environment, the executed action is the mean of all agent actions.
5. Centralized critics observe the global state and all actions; actors use local
   observations only.

Limitation:
This is a preliminary MADDPG baseline for the current simplified environment. It does
not yet implement joint power-subband allocation, SINR coupling, rate-based Jain
fairness, or energy causality.
"""

import os
import time
import random
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf


@dataclass(frozen=True)
class Config:
    num_agents: int = 10
    max_episodes: int = 2000
    max_episode_steps: int = 100

    gamma: float = 0.9
    tau: float = 0.01

    replay_capacity: int = 100_000
    batch_size: int = 64
    warmup_steps: int = 1_000

    actor_lr: float = 0.002
    critic_lr: float = 0.004
    hidden_dim: int = 128

    action_dim_per_agent: int = 1
    action_bound: float = 1.0

    ou_theta: float = 0.15
    ou_sigma_start: float = 0.20
    ou_sigma_end: float = 0.05
    ou_dt: float = 1.0

    energy_weight: float = 0.1

    master_seed: int = 0
    environment_seed: int = 0
    exploration_seed: int = 1000
    replay_seed: int = 2000

    checkpoint_interval: int = 100
    update_every: int = 1

    # Set True only for a short compatibility test.
    quick_test: bool = False


CFG = Config()
EPS = 1e-6


def set_global_seed(seed: int) -> None:
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.keras.utils.set_random_seed(seed)


class FixedTrajectoryBank:
    """Algorithm-independent user motion and common-state trajectories."""

    def __init__(
        self,
        path: str,
        episodes: int,
        steps: int,
        num_agents: int,
        seed: int,
    ) -> None:
        self.path = Path(path)
        self.episodes = int(episodes)
        self.steps = int(steps)
        self.num_agents = int(num_agents)
        self.seed = int(seed)

        if self.path.exists():
            data = np.load(self.path, allow_pickle=False)
            self.initial_user_positions = data["initial_user_positions"]
            self.initial_other_states = data["initial_other_states"]
            self.user_position_deltas = data["user_position_deltas"]
            self.other_state_deltas = data["other_state_deltas"]

            expected = {
                "initial_user_positions": (episodes, num_agents, 2),
                "initial_other_states": (episodes, 4),
                "user_position_deltas": (episodes, steps, num_agents, 2),
                "other_state_deltas": (episodes, steps, 4),
            }
            actual = {
                "initial_user_positions": self.initial_user_positions.shape,
                "initial_other_states": self.initial_other_states.shape,
                "user_position_deltas": self.user_position_deltas.shape,
                "other_state_deltas": self.other_state_deltas.shape,
            }
            if actual != expected:
                raise ValueError(
                    "Existing trajectory file has incompatible shapes.\n"
                    f"Expected: {expected}\nActual: {actual}\n"
                    f"Delete {self.path} and rerun."
                )
        else:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            rng = np.random.RandomState(self.seed)

            self.initial_user_positions = rng.randn(
                episodes, num_agents, 2
            ).astype(np.float32)
            self.initial_other_states = rng.randn(
                episodes, 4
            ).astype(np.float32)
            self.user_position_deltas = (
                rng.randn(episodes, steps, num_agents, 2) * 0.1
            ).astype(np.float32)
            self.other_state_deltas = (
                rng.randn(episodes, steps, 4) * 0.1
            ).astype(np.float32)

            np.savez_compressed(
                self.path,
                initial_user_positions=self.initial_user_positions,
                initial_other_states=self.initial_other_states,
                user_position_deltas=self.user_position_deltas,
                other_state_deltas=self.other_state_deltas,
                environment_seed=np.int32(self.seed),
            )
            print("Created fixed environment trajectories:", self.path)

    def reset(self, episode_index: int) -> tuple[np.ndarray, np.ndarray]:
        return (
            self.initial_user_positions[episode_index].copy(),
            self.initial_other_states[episode_index].copy(),
        )

    def step_delta(
        self, episode_index: int, step_index: int
    ) -> tuple[np.ndarray, np.ndarray]:
        return (
            self.user_position_deltas[episode_index, step_index],
            self.other_state_deltas[episode_index, step_index],
        )


class MultiAgentReplayBuffer:
    def __init__(
        self,
        capacity: int,
        global_state_dim: int,
        joint_action_dim: int,
        seed: int,
    ) -> None:
        self.capacity = int(capacity)
        self.pointer = 0
        self.size = 0
        self.rng = np.random.RandomState(seed)

        self.states = np.zeros((capacity, global_state_dim), np.float32)
        self.actions = np.zeros((capacity, joint_action_dim), np.float32)
        self.rewards = np.zeros((capacity, 1), np.float32)
        self.next_states = np.zeros((capacity, global_state_dim), np.float32)
        self.dones = np.zeros((capacity, 1), np.float32)

    def store(
        self,
        state: np.ndarray,
        joint_action: np.ndarray,
        reward: float,
        next_state: np.ndarray,
        done: bool,
    ) -> None:
        index = self.pointer % self.capacity
        self.states[index] = np.asarray(state, np.float32).reshape(-1)
        self.actions[index] = np.asarray(joint_action, np.float32).reshape(-1)
        self.rewards[index, 0] = float(reward)
        self.next_states[index] = np.asarray(next_state, np.float32).reshape(-1)
        self.dones[index, 0] = float(done)
        self.pointer += 1
        self.size = min(self.size + 1, self.capacity)

    def sample(self, batch_size: int):
        if self.size < batch_size:
            raise RuntimeError(
                f"Replay buffer has {self.size} samples, batch_size={batch_size}."
            )
        indices = self.rng.choice(self.size, size=batch_size, replace=False)
        return (
            tf.convert_to_tensor(self.states[indices]),
            tf.convert_to_tensor(self.actions[indices]),
            tf.convert_to_tensor(self.rewards[indices]),
            tf.convert_to_tensor(self.next_states[indices]),
            tf.convert_to_tensor(self.dones[indices]),
        )


class OrnsteinUhlenbeckNoise:
    def __init__(
        self,
        num_agents: int,
        action_dim: int,
        theta: float,
        sigma_start: float,
        sigma_end: float,
        dt: float,
        total_steps: int,
        seed: int,
    ) -> None:
        self.theta = float(theta)
        self.sigma_start = float(sigma_start)
        self.sigma_end = float(sigma_end)
        self.dt = float(dt)
        self.total_steps = max(int(total_steps), 1)
        self.rng = np.random.RandomState(seed)
        self.state = np.zeros((num_agents, action_dim), np.float32)

    def reset(self) -> None:
        self.state.fill(0.0)

    def current_sigma(self, global_step: int) -> float:
        ratio = min(max(global_step / self.total_steps, 0.0), 1.0)
        return self.sigma_start + ratio * (self.sigma_end - self.sigma_start)

    def sample(self, global_step: int) -> np.ndarray:
        sigma = self.current_sigma(global_step)
        random_term = self.rng.randn(*self.state.shape).astype(np.float32)
        drift = -self.theta * self.state * self.dt
        diffusion = sigma * np.sqrt(self.dt) * random_term
        self.state = self.state + drift + diffusion
        return self.state.copy()


class Actor(tf.keras.Model):
    def __init__(
        self,
        hidden_dim: int,
        action_dim: int,
        action_bound: float,
        name: str,
    ) -> None:
        super().__init__(name=name)
        self.action_bound = float(action_bound)
        self.fc1 = tf.keras.layers.Dense(hidden_dim, activation="relu")
        self.fc2 = tf.keras.layers.Dense(hidden_dim, activation="relu")
        self.fc3 = tf.keras.layers.Dense(hidden_dim, activation="relu")
        self.out = tf.keras.layers.Dense(action_dim, activation="tanh")

    def call(self, local_observation, training=False):
        del training
        x = self.fc1(local_observation)
        x = self.fc2(x)
        x = self.fc3(x)
        return 0.5 * (self.out(x) + 1.0) * self.action_bound


class CentralizedCritic(tf.keras.Model):
    def __init__(self, hidden_dim: int, name: str) -> None:
        super().__init__(name=name)
        self.fc1 = tf.keras.layers.Dense(hidden_dim, activation="relu")
        self.fc2 = tf.keras.layers.Dense(hidden_dim, activation="relu")
        self.fc3 = tf.keras.layers.Dense(hidden_dim, activation="relu")
        self.out = tf.keras.layers.Dense(1)

    def call(self, inputs, training=False):
        del training
        global_state, joint_action = inputs
        x = tf.concat([global_state, joint_action], axis=1)
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        return self.out(x)


class MADDPG:
    def __init__(
        self,
        original_state_dim: int,
        global_state_dim: int,
        local_observation_dim: int,
        cfg: Config,
    ) -> None:
        self.cfg = cfg
        self.num_agents = cfg.num_agents
        self.original_state_dim = original_state_dim
        self.joint_action_dim = cfg.num_agents * cfg.action_dim_per_agent

        self.actors = []
        self.target_actors = []
        self.critics = []
        self.target_critics = []
        self.actor_optimizers = []
        self.critic_optimizers = []

        for i in range(self.num_agents):
            actor = Actor(cfg.hidden_dim, cfg.action_dim_per_agent, cfg.action_bound, f"Actor_{i}")
            target_actor = Actor(cfg.hidden_dim, cfg.action_dim_per_agent, cfg.action_bound, f"TargetActor_{i}")
            critic = CentralizedCritic(cfg.hidden_dim, f"Critic_{i}")
            target_critic = CentralizedCritic(cfg.hidden_dim, f"TargetCritic_{i}")

            self.actors.append(actor)
            self.target_actors.append(target_actor)
            self.critics.append(critic)
            self.target_critics.append(target_critic)
            self.actor_optimizers.append(tf.keras.optimizers.Adam(cfg.actor_lr))
            self.critic_optimizers.append(tf.keras.optimizers.Adam(cfg.critic_lr))

        dummy_global = tf.zeros((1, global_state_dim), tf.float32)
        dummy_local = tf.zeros((1, local_observation_dim), tf.float32)
        dummy_joint = tf.zeros((1, self.joint_action_dim), tf.float32)

        for i in range(self.num_agents):
            self.actors[i](dummy_local)
            self.target_actors[i](dummy_local)
            self.critics[i]((dummy_global, dummy_joint))
            self.target_critics[i]((dummy_global, dummy_joint))
            self.target_actors[i].set_weights(self.actors[i].get_weights())
            self.target_critics[i].set_weights(self.critics[i].get_weights())

            if hasattr(self.actor_optimizers[i], "build"):
                self.actor_optimizers[i].build(self.actors[i].trainable_variables)
            if hasattr(self.critic_optimizers[i], "build"):
                self.critic_optimizers[i].build(self.critics[i].trainable_variables)

        self.memory = MultiAgentReplayBuffer(
            cfg.replay_capacity,
            global_state_dim,
            self.joint_action_dim,
            cfg.replay_seed,
        )

    def extract_local_observation(self, global_state, agent_index: int):
        current_offset = 0
        previous_offset = self.original_state_dim

        current_common = global_state[:, current_offset:current_offset + 4]
        cp = current_offset + 4 + 2 * agent_index
        current_position = global_state[:, cp:cp + 2]

        previous_common = global_state[:, previous_offset:previous_offset + 4]
        pp = previous_offset + 4 + 2 * agent_index
        previous_position = global_state[:, pp:pp + 2]

        return tf.concat(
            [current_common, current_position, previous_common, previous_position],
            axis=1,
        )

    def choose_actions(self, global_state: np.ndarray, exploration_noise=None):
        state_tensor = tf.convert_to_tensor(
            np.asarray(global_state, np.float32).reshape(1, -1)
        )
        actions = []
        for i in range(self.num_agents):
            local_obs = self.extract_local_observation(state_tensor, i)
            actions.append(self.actors[i](local_obs, training=False).numpy()[0])
        joint_actions = np.stack(actions, axis=0).astype(np.float32)
        if exploration_noise is not None:
            joint_actions = joint_actions + exploration_noise
        return np.clip(joint_actions, 0.0, self.cfg.action_bound)

    def store_transition(self, state, actions, reward, next_state, done):
        self.memory.store(state, actions.reshape(-1), reward, next_state, done)

    @tf.function(reduce_retracing=True)
    def _train_step(self, states, joint_actions, rewards, next_states, dones):
        next_target_actions = []
        for i in range(self.num_agents):
            next_local = self.extract_local_observation(next_states, i)
            next_target_actions.append(self.target_actors[i](next_local, training=False))
        next_target_joint = tf.concat(next_target_actions, axis=1)

        actor_losses = []
        critic_losses = []

        for i in range(self.num_agents):
            with tf.GradientTape() as critic_tape:
                target_q = self.target_critics[i]((next_states, next_target_joint), training=False)
                q_target = rewards + self.cfg.gamma * (1.0 - dones) * target_q
                q_target = tf.stop_gradient(q_target)
                current_q = self.critics[i]((states, joint_actions), training=True)
                critic_loss = tf.reduce_mean(tf.square(current_q - q_target))

            critic_vars = self.critics[i].trainable_variables
            critic_grads = critic_tape.gradient(critic_loss, critic_vars)
            self.critic_optimizers[i].apply_gradients(
                [(g, v) for g, v in zip(critic_grads, critic_vars) if g is not None]
            )

            with tf.GradientTape() as actor_tape:
                policy_actions = []
                for j in range(self.num_agents):
                    local = self.extract_local_observation(states, j)
                    a_j = self.actors[j](local, training=(j == i))
                    if j != i:
                        a_j = tf.stop_gradient(a_j)
                    policy_actions.append(a_j)
                policy_joint = tf.concat(policy_actions, axis=1)
                q_pi = self.critics[i]((states, policy_joint), training=False)
                actor_loss = -tf.reduce_mean(q_pi)

            actor_vars = self.actors[i].trainable_variables
            actor_grads = actor_tape.gradient(actor_loss, actor_vars)
            self.actor_optimizers[i].apply_gradients(
                [(g, v) for g, v in zip(actor_grads, actor_vars) if g is not None]
            )

            actor_losses.append(actor_loss)
            critic_losses.append(critic_loss)

        for i in range(self.num_agents):
            for source, target in zip(self.actors[i].weights, self.target_actors[i].weights):
                target.assign((1.0 - self.cfg.tau) * target + self.cfg.tau * source)
            for source, target in zip(self.critics[i].weights, self.target_critics[i].weights):
                target.assign((1.0 - self.cfg.tau) * target + self.cfg.tau * source)

        return tf.stack(actor_losses), tf.stack(critic_losses)

    def learn(self):
        actor_losses, critic_losses = self._train_step(*self.memory.sample(self.cfg.batch_size))
        actor_np = actor_losses.numpy()
        critic_np = critic_losses.numpy()
        return {
            "actor_losses": actor_np,
            "critic_losses": critic_np,
            "actor_loss_mean": float(np.mean(actor_np)),
            "critic_loss_mean": float(np.mean(critic_np)),
        }


def jain_fairness_index(channel_gains: np.ndarray) -> float:
    channel_gains = np.asarray(channel_gains, np.float32)
    return float(
        np.sum(channel_gains) ** 2
        / (len(channel_gains) * np.sum(channel_gains ** 2) + EPS)
    )


def effective_scalar_action(joint_actions: np.ndarray) -> float:
    return float(np.mean(np.asarray(joint_actions, np.float32)))


def energy_consumption(scalar_action: float) -> float:
    return float(scalar_action ** 2)


def reward_function(channel_gains, scalar_action: float, energy_weight: float) -> float:
    channel_reward = abs(np.sum(channel_gains * scalar_action))
    fairness = jain_fairness_index(channel_gains)
    energy_penalty = energy_consumption(scalar_action)
    return float(channel_reward * fairness - energy_weight * energy_penalty)


def save_results(
    path: str,
    completed_episodes: int,
    episode_rewards,
    episode_fairness_last,
    episode_energy_last,
    episode_fairness_mean,
    episode_energy_mean,
    episode_effective_action_mean,
    episode_joint_action_std_mean,
    actor_loss_means,
    critic_loss_means,
    per_agent_actor_losses,
    per_agent_critic_losses,
    running_time_seconds: float,
    fixed_trajectory_path: str,
) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        path,
        algorithm=np.asarray("MADDPG"),
        master_seed=np.int32(CFG.master_seed),
        environment_seed=np.int32(CFG.environment_seed),
        exploration_seed=np.int32(CFG.exploration_seed),
        replay_seed=np.int32(CFG.replay_seed),
        tensorflow_version=np.asarray(tf.__version__),
        keras_version=np.asarray(getattr(tf.keras, "__version__", "unknown")),
        completed_episodes=np.int32(completed_episodes),
        max_episode_steps=np.int32(CFG.max_episode_steps),
        num_agents=np.int32(CFG.num_agents),
        action_aggregation=np.asarray("mean"),
        fixed_trajectory_path=np.asarray(fixed_trajectory_path),
        ep_rewardall=np.asarray(episode_rewards, np.float32),
        ep_fairness=np.asarray(episode_fairness_last, np.float32),
        ep_energy=np.asarray(episode_energy_last, np.float32),
        ep_fairness_mean=np.asarray(episode_fairness_mean, np.float32),
        ep_energy_mean=np.asarray(episode_energy_mean, np.float32),
        ep_effective_action_mean=np.asarray(episode_effective_action_mean, np.float32),
        ep_joint_action_std_mean=np.asarray(episode_joint_action_std_mean, np.float32),
        actor_loss_means=np.asarray(actor_loss_means, np.float32),
        critic_loss_means=np.asarray(critic_loss_means, np.float32),
        per_agent_actor_losses=np.asarray(per_agent_actor_losses, np.float32),
        per_agent_critic_losses=np.asarray(per_agent_critic_losses, np.float32),
        running_time_seconds=np.float32(running_time_seconds),
    )


def main() -> None:
    set_global_seed(CFG.master_seed)

    print("TensorFlow version:", tf.__version__)
    print("Keras version:", getattr(tf.keras, "__version__", "unknown"))
    print("Eager execution:", tf.executing_eagerly())

    max_episodes = 20 if CFG.quick_test else CFG.max_episodes
    max_episode_steps = 20 if CFG.quick_test else CFG.max_episode_steps
    warmup_steps = 100 if CFG.quick_test else CFG.warmup_steps

    original_state_dim = 4 + 2 * CFG.num_agents
    global_state_dim = 2 * original_state_dim
    local_observation_dim = 12

    data_dir = Path("data")
    data_dir.mkdir(parents=True, exist_ok=True)

    trajectory_path = data_dir / (
        f"fixed_env_trajectory_seed{CFG.environment_seed}_"
        f"ep{max_episodes}_steps{max_episode_steps}_K{CFG.num_agents}.npz"
    )
    trajectories = FixedTrajectoryBank(
        str(trajectory_path),
        max_episodes,
        max_episode_steps,
        CFG.num_agents,
        CFG.environment_seed,
    )

    maddpg = MADDPG(
        original_state_dim,
        global_state_dim,
        local_observation_dim,
        CFG,
    )

    total_training_steps = max_episodes * max_episode_steps
    ou_noise = OrnsteinUhlenbeckNoise(
        CFG.num_agents,
        CFG.action_dim_per_agent,
        CFG.ou_theta,
        CFG.ou_sigma_start,
        CFG.ou_sigma_end,
        CFG.ou_dt,
        total_training_steps,
        CFG.exploration_seed,
    )
    warmup_rng = np.random.RandomState(CFG.exploration_seed + 1)

    start_time = time.time()
    global_step = 0

    episode_rewards = []
    episode_fairness_last = []
    episode_energy_last = []
    episode_fairness_mean = []
    episode_energy_mean = []
    episode_effective_action_mean = []
    episode_joint_action_std_mean = []

    actor_loss_means = []
    critic_loss_means = []
    per_agent_actor_losses = []
    per_agent_critic_losses = []

    for episode in range(max_episodes):
        user_positions, other_state = trajectories.reset(episode)
        current_original_state = np.concatenate(
            [other_state.flatten(), user_positions.flatten()]
        ).astype(np.float32)
        previous_original_state = np.zeros_like(current_original_state)
        global_state = np.concatenate(
            [current_original_state, previous_original_state]
        ).astype(np.float32)

        ou_noise.reset()
        episode_reward = 0.0
        fairness_values = []
        energy_values = []
        effective_action_values = []
        joint_action_std_values = []
        latest_losses = None

        for step in range(max_episode_steps):
            if global_step < warmup_steps:
                joint_actions = warmup_rng.uniform(
                    0.0,
                    CFG.action_bound,
                    size=(CFG.num_agents, CFG.action_dim_per_agent),
                ).astype(np.float32)
            else:
                exploration = ou_noise.sample(global_step)
                joint_actions = maddpg.choose_actions(
                    global_state,
                    exploration_noise=exploration,
                )

            scalar_action = effective_scalar_action(joint_actions)

            user_delta, other_delta = trajectories.step_delta(episode, step)
            user_positions = user_positions + user_delta
            other_state = other_state + other_delta

            next_original_state = np.concatenate(
                [other_state.flatten(), user_positions.flatten()]
            ).astype(np.float32)
            next_global_state = np.concatenate(
                [next_original_state, current_original_state]
            ).astype(np.float32)

            distances = np.sqrt(np.sum(user_positions ** 2, axis=1))
            channel_gains = 1.0 / (1.0 + distances)
            reward = reward_function(channel_gains, scalar_action, CFG.energy_weight)
            fairness = jain_fairness_index(channel_gains)
            energy = energy_consumption(scalar_action)
            done = step == max_episode_steps - 1

            maddpg.store_transition(
                global_state,
                joint_actions,
                reward,
                next_global_state,
                done,
            )

            if (
                maddpg.memory.size >= max(warmup_steps, CFG.batch_size)
                and global_step % CFG.update_every == 0
            ):
                latest_losses = maddpg.learn()
                actor_loss_means.append(latest_losses["actor_loss_mean"])
                critic_loss_means.append(latest_losses["critic_loss_mean"])
                per_agent_actor_losses.append(latest_losses["actor_losses"])
                per_agent_critic_losses.append(latest_losses["critic_losses"])

            episode_reward += reward
            fairness_values.append(fairness)
            energy_values.append(energy)
            effective_action_values.append(scalar_action)
            joint_action_std_values.append(float(np.std(joint_actions)))

            current_original_state = next_original_state.copy()
            global_state = next_global_state.copy()
            global_step += 1

        episode_rewards.append(float(episode_reward))
        episode_fairness_last.append(float(fairness_values[-1]))
        episode_energy_last.append(float(energy_values[-1]))
        episode_fairness_mean.append(float(np.mean(fairness_values)))
        episode_energy_mean.append(float(np.mean(energy_values)))
        episode_effective_action_mean.append(float(np.mean(effective_action_values)))
        episode_joint_action_std_mean.append(float(np.mean(joint_action_std_values)))

        if latest_losses is None:
            loss_text = "warming up"
        else:
            loss_text = (
                f"actor_mean={latest_losses['actor_loss_mean']:.4f}, "
                f"critic_mean={latest_losses['critic_loss_mean']:.4f}, "
                f"OU_sigma={ou_noise.current_sigma(global_step):.4f}"
            )

        print(
            f"Episode {episode + 1:4d}/{max_episodes} | "
            f"Reward={episode_reward:10.4f} | "
            f"Fairness(last)={fairness_values[-1]:.4f} | "
            f"Energy(last)={energy_values[-1]:.4f} | "
            f"EffectiveAction(mean)={np.mean(effective_action_values):.4f} | "
            f"{loss_text}"
        )

        if (episode + 1) % CFG.checkpoint_interval == 0:
            elapsed = time.time() - start_time
            checkpoint_path = data_dir / (
                f"maddpg_checkpoint_seed{CFG.master_seed}_ep{episode + 1}.npz"
            )
            save_results(
                str(checkpoint_path),
                episode + 1,
                episode_rewards,
                episode_fairness_last,
                episode_energy_last,
                episode_fairness_mean,
                episode_energy_mean,
                episode_effective_action_mean,
                episode_joint_action_std_mean,
                actor_loss_means,
                critic_loss_means,
                per_agent_actor_losses,
                per_agent_critic_losses,
                elapsed,
                str(trajectory_path),
            )
            print("Checkpoint saved:", checkpoint_path)

    running_time = time.time() - start_time
    print(f"Running time: {running_time:.2f} seconds")

    final_path = data_dir / f"data_maddpg_keras3_seed{CFG.master_seed}.npz"
    save_results(
        str(final_path),
        max_episodes,
        episode_rewards,
        episode_fairness_last,
        episode_energy_last,
        episode_fairness_mean,
        episode_energy_mean,
        episode_effective_action_mean,
        episode_joint_action_std_mean,
        actor_loss_means,
        critic_loss_means,
        per_agent_actor_losses,
        per_agent_critic_losses,
        running_time,
        str(trajectory_path),
    )
    print("Saved final results to:", final_path)

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(episode_rewards, label="MADDPG reward")
    plt.xlabel("Episode")
    plt.ylabel("Episodic Reward")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(episode_fairness_mean, label="Mean fairness")
    plt.xlabel("Episode")
    plt.ylabel("Jain Fairness Index")
    plt.legend()
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(episode_energy_mean, label="Mean energy consumption")
    plt.xlabel("Episode")
    plt.ylabel("Energy")
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(episode_effective_action_mean, label="Mean effective action")
    plt.xlabel("Episode")
    plt.ylabel("Action")
    plt.legend()
    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
